### ISSUE TITLE
Regarding log fold change and predict.py description

### ISSUE THREAD

**Issue by jeffmylife** [FunctionLab/ExPecto#1]
Hey, 
the paper mentioned that the variant expression effect prediction is measured by the log(fold change) but I cannot find any log transformations in either chromatin.py or predict.py. 
I do see in predict.py @line106 there is a standard difference (a-b), not a log fold change.  
**Am I missing something?**

Also, the predict.py description at the top is the same as chromatin.py. 

Thanks

**Comment by jzthree** [comment]
The expression levels are always represented by log-transformed values, therefore all predictions are already in log scale and difference of predictions means log fold change.

Thanks for pointing out the issue in the script description! Fixed now.
