### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by vagarwal87** [FunctionLab/ExPecto#11]
Hi, I was trying to run your example:

python ./train.py --expFile ./resources/geneanno.exp.csv --targetIndex 1 --output model.adipose

However with ~11Gb memory on GPU (Tesla K80) the script gets killed, presumably due to running out of memory.

Could you please give us a sense of the memory requirements and hardware resources required to run this type of model?

Thanks!
Vikram

**Comment by jzthree** [comment]
Hi Vikram, 

In my test, it uses about 13 G of CPU memory. Train.py uses CPU to train the linear model part of expression models so you actually don't need a GPU to run it.  

Best,
Jian

**Comment by vagarwal87** [comment]
Ah okay, that makes sense, thank you for the response!

Best,
Vikram
