### ISSUE TITLE
Regarding chromatin.py

### ISSUE THREAD

**Issue by Pankaj01998** [FunctionLab/ExPecto#13]
when I was running the python script chromatin.py, I got the following error

Traceback (most recent call last):
  File "chromatin.py", line 34, in <module>
    genome = pyfasta.Fasta('./resources/hg19.fa')
  File "/home/pankaj/.local/lib/python3.5/site-packages/pyfasta/fasta.py", line 67, in __init__
    raise FastaNotFound('"' + fasta_name + '"')
pyfasta.fasta.FastaNotFound: "./resources/hg19.fa"

I think hg19.fa file is not present in resource folder.
Plese help.

**Comment by jzthree** [comment]
You can download the resources files `sh download_resources.sh; tar xf resources.tar.gz` as described in the `Install` section.
