### ISSUE TITLE
Availability of embeddings for deepsea.beluga model

### ISSUE THREAD

**Issue by kmualim** [FunctionLab/ExPecto#14]
Hi, 

Thank you for the model as well as releasing the code. 
Are any of the learned embeddings from the ExPecTo architecture made available? 

Thanks, 
Kristy

**Comment by jzthree** [comment]
Yes you can load the model and extract the weights of the last linear layer - is this what you need?

**Comment by kmualim** [comment]
Hi, 

So not exactly - I apologize for not being clear previously. The ExPecto framework first consists of a deep NN that takes in input sequences to epigenomic features. In the methods section of the paper, it was quoted: 
"the deep convolutional neural network model scanned the genomic sequence between + 20 kb upstream and –20 kb downstream to predict spatial chromatin organization patterns by using a moving window with a 200-bp step size, which yielded 200 spatial bins with a total number of 400,400 features." 
I was wondering if these 400,400 features are made available? 

Thanks.

**Comment by jzthree** [comment]
Currently we only made available the spatially transformed features which are computed from the 400,400 features - it is under `resources/Xreducedall.2002.npy` if you download and extract the resources.

**Comment by kmualim** [comment]
Ah okay, thanks!

**Comment by Jasonxu0109** [comment]
> Currently we only made available the spatially transformed features which are computed from the 400,400 features - it is under `resources/Xreducedall.2002.npy` if you download and extract the resources.

I want to konw how these 400,400 features are made from narrowpeak bed file? Could you provide the python script?
