### ISSUE TITLE
Ordering of 2002 output tasks of deepsea beluga model

### ISSUE THREAD

**Issue by blindauth** [FunctionLab/ExPecto#15]
Would you be willing to share the order of the output tasks in the deepsea beluga model? Analogous to https://github.com/kipoi/models/blob/master/DeepSEA/predictor.names

**Comment by jzthree** [comment]
Yes I have added this information to the repository in a recent commit 7b04799b234a1177ef46609074dfeca2d032927c - you can find it at 
 `resources/deepsea_beluga_2002_features.tsv`. Thank you for asking! Feel free to reopen this if it does not address your question.

**Comment by imk1** [comment]
Thanks for sharing this!  Do you have a brief description of what each of the cell lines is?  Thanks!
