### ISSUE TITLE
NA values after using BEDOPS closest-features to get associated genes

### ISSUE THREAD

**Issue by washedgram** [FunctionLab/ExPecto#16]
I can successfully run the closest-features command strip in the README with my own files but my output file only has five columns and the last two only say NA. Any advice as to the source of my error? My .vcf output file from chromatin.py is formatted correctly.

**Comment by jzthree** [comment]
One possibility is that your vcf file have chromosome names that do not contain 'chr', could you try this updated snippet that addresses that?

`closest-features --delim '\t' --closest --dist <(awk '{printf $1"\t"$2-1"\t"$2"\n"}' ./example/example.vcf|sed s/chr//g|sed s/^/chr/g|sort-bed - ) ./resources/geneanno.pc.sorted.bed > ./example/example.vcf.bed.sorted.bed.closestgene
`

**Comment by washedgram** [comment]
Sorry for the late reply, haven't been on my computer for the past week.

Updated snippet works. Thanks!
