### ISSUE TITLE
Cell Line Description for Belgua

### ISSUE THREAD

**Issue by imk1** [FunctionLab/ExPecto#25]
Do you have a short description of what each of the cell lines used in Beluga are?  Thanks!

**Comment by jzthree** [comment]
Do you mean beyond cell line name here https://github.com/FunctionLab/ExPecto/blob/master/resources/deepsea_beluga_2002_features.tsv ? The only place that I know have such information is ENCODE controlled vocabulary, and you can find information for Roadmap Epigenomics in the Roadmap epigenomics website metadata file https://egg2.wustl.edu/roadmap/web_portal/meta.html.

**Comment by imk1** [comment]
I was hoping for something more detailed than deepsea_beluga_2002_features.tsv, and I think that the Roadmap link you put has that.  Thank you!
