### ISSUE TITLE
Download resources link no longer active

### ISSUE THREAD

**Issue by pkathail** [FunctionLab/ExPecto#27]
Hi,

I was attempting to download the resources files from this link: http://deepsea.princeton.edu/media/code/expecto/resources_20190807.tar.gz but it seems it's no longer active. Is there another place I could download the data associated with this repository. Specifically, I was looking for the `Xreducedall.2002.npy` file

Thanks!
Pooja

**Comment by jzthree** [comment]
There was a temporary downtime for the deepsea website. It should be back
now.

Jian

**Comment by pkathail** [comment]
I'm able to download it now, thank you!

**Comment by yangzhao1230** [comment]
I encountered the same issue. Could you please provide guidance on how to download the resources at this time

**Comment by atadych** [comment]
@yangzhao1230 Should be available under [https://deepsea.princeton.edu/media/code/expecto/resources_20190807.tar.gz](https://deepsea.princeton.edu/media/code/expecto/resources_20190807.tar.gz)
