### ISSUE TITLE
Treatment of TSS itself

### ISSUE THREAD

**Issue by jiequan35** [FunctionLab/ExPecto#7]
Hi,

In the ExPecto paper in nature genetics, you said that training was performed by using ±20kb hg19 sequence "surrounding" its representative TSS.
Literally, did you NOT include the base of the representative TSS in any 200-bp bin (but include 1,800-bp surrounding context sequence)?

Best regards,
Luan

**Comment by jzthree** [comment]
Hi Luan,

No it does include TSS. Let's call 0 as the TSS position, then it uses  -19,999 - 19999 (inclusion on both end). More specifically it uses -19,999 - 0 (100 bins ) and 0-19,999 (100bins).  

Best,
Jian

**Comment by jiequan35** [comment]
Hi Jian,

Thank you for kind response!

Best,
Jian.
